#' -----------------------------------------------------------------------------
#' Aim: Gather processed tracking data for Vultures, covering different studies,
#' for testing purposes. Study-specific data is generated by running an offline
#' simulation of the developed study-level workflow, which involves a series of
#' Apps developed in this project. Source code for these apps must be available
#' locally and the offline workflow was built on a separate R project
#' ("Workflows_simulator"), which must also be available locally.
#' ----------------------------------------------------------------------------

# ----------------------- #
# ----     Preamble   -----
# ----------------------- #

require(fs)
require(move2)
require(dplyr)
require(readr)
require(lubridate)
require(withr)
require(httr2)
require(keyring)
require(clock)

options(dplyr.width = Inf)

source("../../MoveApps_workflow_simulator/fcts_apps_wrappers.R")
source("../../MoveApps_workflow_simulator/helpers.r")
source("../../MoveApps_workflow_simulator/fcts_study_level_workflows.R")
source("tests/app-testing-helpers.r")

proj_key <- get_proj_key()
app_key <- get_app_key()

mvbk_creds <- httr2::secret_read_rds("../../MoveApps_workflow_simulator/mvbk_creds.rds", key = I(proj_key))

apps_paths <- list(
  mvbkloc = "../Movebank-Loc-move2/",
  localsolar = "../Convert-Times/",
  stand = "../Standardise_Formats_and_Calculate_Basic_Statistics/",
  fetch_acc = "../Fetch_and_Merge_Acceleration_to_Locations/",
  classif = "../Behavioural_Classification_for_Vultures/",
  clust = "../Avian_Cluster_Detection/",
  clust_metrics = "../Generate_Avian_Cluster_Metrics//"
)


# download apps' package dependencies
apps_deps <- lapply(
  apps_paths, function(path){
    renv::dependencies(paste0(path, "RFunction.r"))$Package
  }
) |>
  unlist() |>
  unique()

pak::pkg_install(apps_deps)


# ----------------------------------------------- #
# ----    Run study-level Workflows (offline)  -----
# ----------------------------------------------- #

tm_end <- as.POSIXct("2024-04-20 00:00:00", tz = "UTC")


nam <- study_level_wf(
  apps_paths = apps_paths,
  mvbk_usr = mvbk_creds$scavengersonpatrol$usr, 
  mvbk_pwd = mvbk_creds$scavengersonpatrol$pwd,
  study_name = "AVulture Namibia SOP", 
  animal_ids = c("TO_6485", "GA_6594", "TO_6032", "TO_6220"),
  tm_start = tm_end - days(15),
  tm_end = tm_end, 
  loc_tm_thin_mins = 3
) |> 
  cluster_app(
    clustercode = "NAM",
    path_to_app = apps_paths$clust
  ) |> 
  cluster_metrics_app(
    cluster_tbl_type = "track-and-whole",
    path_to_app = apps_paths$clust_metrics)



nam_loc <- study_level_wf(
  apps_paths = apps_paths,
  mvbk_usr = mvbk_creds$scavengersonpatrol$usr, 
  mvbk_pwd = mvbk_creds$scavengersonpatrol$pwd,
  study_name = "AVulture Namibia SOP", 
  animal_ids = c("TO_6485", "GA_6594", "TO_6032", "TO_6220"),
  tm_start = tm_end - days(10),
  tm_end = tm_end, 
  loc_tm_thin_mins = 3
) |> 
  cluster_app(
    clustercode = "NAM",
    path_to_app = apps_paths$clust
  ) |> 
  cluster_metrics_app(
    output_type = "merge-to-locs",
    path_to_app = apps_paths$clust_metrics
  )






movebank_remove_credentials()

sa_vfa <- study_level_wf(
  apps_paths = apps_paths,
  mvbk_usr = mvbk_creds$mlmackenzie$usr, 
  mvbk_pwd = mvbk_creds$mlmackenzie$pwd,
  study_name = "South Africa vultures VfA MPIAB", 
  animal_ids = c("Bateleur_8889", "Bateleur_8887", "White-headed_8888"),
  tm_start = tm_end - days(15),
  tm_end = tm_end
) |> 
  cluster_app(
    clustercode = "SA",
    path_to_app = apps_paths$clust, 
    clusterwindow = 5, 
    clusterstep = 1, 
    match_thresh = 100
  ) |> 
  cluster_metrics_app(
    cluster_tbl_type = "whole-only",
    path_to_app = apps_paths$clust_metrics)




ken_tnz <- study_level_wf(
  apps_paths = apps_paths,
  mvbk_usr = mvbk_creds$mlmackenzie$usr, 
  mvbk_pwd = mvbk_creds$mlmackenzie$pwd,
  study_name = 103394406, #"Gyps africanus Kendall Tanzania$", 
  animal_ids = c("ST1104A", "ST1008A", "ST1035A", "C175593", "A234556", "ST970A",
                 "ST1111A", "ST1081A", "ST1087A"),
  tm_start = tm_end - days(20),
  tm_end = tm_end
) |> 
  cluster_app(
    clustercode = "TZN",
    path_to_app = apps_paths$clust, 
    clusterwindow = 10, 
    clusterstep = 3
  ) |> 
  cluster_metrics_app(
    cluster_tbl_type = "track-and-whole",
    path_to_app = apps_paths$clust_metrics)



savahn <- study_level_wf(
  apps_paths = apps_paths,
  mvbk_usr = mvbk_creds$mlmackenzie$usr, 
  mvbk_pwd = mvbk_creds$mlmackenzie$pwd,
  study_name = "Savannah-MEFT", 
  animal_ids = c("SAV-4360-A", "SAV-4355-B", "SAV-4356-A",  "SAV-4386-A", 
                 "SAV-4357-A", "SAV-4358-A"),
  tm_start = tm_end - days(20),
  tm_end = tm_end
) |> 
  cluster_app(
    clustercode = "SAV",
    path_to_app = apps_paths$clust, 
    clusterwindow = 10, 
    clusterstep = 3
  ) |> 
  cluster_metrics_app(
    cluster_tbl_type = "whole-only",
    path_to_app = apps_paths$clust_metrics)





# ---------------------------------------------------------------- #
# ----  Combine test sets in list and export to encrypted file -----
# ---------------------------------------------------------------- #


test_sets <- list(
  nam = nam,
  nam_loc = nam_loc,
  sa_vfa = sa_vfa,
  savahn = savahn,
  ken_tnz = ken_tnz
)

httr2::secret_write_rds(test_sets, path = "data/raw/vult_test_data.rds", key = I(app_key))


# subset for unit testing
unit_test_sets <- test_sets[c("nam", "nam_loc", "savahn")]
httr2::secret_write_rds(unit_test_sets, path = "tests/testthat/data/vult_unit_test_data.rds", key = I(app_key))
